from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    # Request / schema errors (fail-closed)
    GW_ERROR_INVALID_REQUEST = "GW_ERROR_INVALID_REQUEST"
    GW_ERROR_SCHEMA_VERSION = "GW_ERROR_SCHEMA_VERSION"
    GW_ERROR_UNKNOWN_TOP_LEVEL_KEY = "GW_ERROR_UNKNOWN_TOP_LEVEL_KEY"
    GW_ERROR_UNKNOWN_WALLET_KEY = "GW_ERROR_UNKNOWN_WALLET_KEY"
    GW_ERROR_UNKNOWN_TX_KEY = "GW_ERROR_UNKNOWN_TX_KEY"
    GW_ERROR_UNKNOWN_SIGNAL_KEY = "GW_ERROR_UNKNOWN_SIGNAL_KEY"
    GW_ERROR_UNKNOWN_AUTH_KEY = "GW_ERROR_UNKNOWN_AUTH_KEY"
    GW_ERROR_INVALID_MODE = "GW_ERROR_INVALID_MODE"
    GW_ERROR_BAD_NUMBER = "GW_ERROR_BAD_NUMBER"
    GW_ERROR_OVERSIZE = "GW_ERROR_OVERSIZE"

    # Outcomes - tx mode
    GW_OK_HEALTHY_ALLOW = "GW_OK_HEALTHY_ALLOW"
    GW_ESCALATE_ELEVATED = "GW_ESCALATE_ELEVATED"
    GW_DENY_HIGH_OR_CRITICAL = "GW_DENY_HIGH_OR_CRITICAL"

    # Outcomes - qid auth mode
    GW_OK_QID_AUTH_ALLOW = "GW_OK_QID_AUTH_ALLOW"
    GW_ESCALATE_QID_UNTRUSTED_DEVICE = "GW_ESCALATE_QID_UNTRUSTED_DEVICE"
    GW_ESCALATE_QID_SENTINEL_ALERT = "GW_ESCALATE_QID_SENTINEL_ALERT"
    GW_DENY_QID_UNVERIFIED = "GW_DENY_QID_UNVERIFIED"
    GW_DENY_QID_BINDING_REQUIRED = "GW_DENY_QID_BINDING_REQUIRED"
